[package]
name = "noise"
version = "0.1.0"
description = "Generate noise using Perlin and gradient noise functions"
repository = "https://github.com/jneums/noise"
keywords = [ "perlin-noise", "gradient-noise", "noise" ]
license = "MIT"

[dev-dependencies]
test = "2.0.0"

[dependencies]
base = "0.13.0"

[toolchain]
moc = "0.13.0"
